In [20]:
import pandas as pd
import numpy as np
import json

In [21]:
file_name = '/content/receipts.json'

In [22]:
# Load the JSON file
with open(file_name, 'r') as file:
    data = [json.loads(line) for line in file]

In [23]:
# Convert to DataFrame
df = pd.DataFrame(data)

In [24]:
df.head()

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5,{'$date': 1609632000000},1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
4,{'$oid': '5ff1e1d20a7214ada1000561'},5.0,All-receipts receipt bonus,{'$date': 1609687506000},{'$date': 1609687506000},{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687506000},5.0,{'$date': 1609601106000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052

In [25]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 _id                          0
bonusPointsEarned          575
bonusPointsEarnedReason    575
createDate                   0
dateScanned                  0
finishedDate               551
modifyDate                   0
pointsAwardedDate          582
pointsEarned               510
purchaseDate               448
purchasedItemCount         484
rewardsReceiptItemList     440
rewardsReceiptStatus         0
totalSpent                 435
userId                       0
dtype: int64

In [26]:
# Count the total number of rows
total_rows = len(df)

# Count the number of duplicate rows based on '_id'
duplicate_rows = df.duplicated(subset=['_id']).sum()

# Calculate the percentage of duplicate records
percentage_duplicates = (duplicate_rows / total_rows) * 100

print(f"Percentage of Duplicate Records: {percentage_duplicates:.2f}%")

Percentage of Duplicate Records: 0.00%

In [27]:
# Check data types
data_types = df.dtypes
print("Data Types:\n", data_types)

Data Types:
 _id                         object
bonusPointsEarned          float64
bonusPointsEarnedReason     object
createDate                  object
dateScanned                 object
finishedDate                object
modifyDate                  object
pointsAwardedDate           object
pointsEarned                object
purchaseDate                object
purchasedItemCount         float64
rewardsReceiptItemList      object
rewardsReceiptStatus        object
totalSpent                  object
userId                      object
dtype: object

In [28]:
items_df = pd.json_normalize(df['rewardsReceiptItemList'])

# Print the normalized DataFrame for 'rewardsReceiptItemList'
print("\nNormalized rewardsReceiptItemList DataFrame:")
print(items_df)

Normalized rewardsReceiptItemList DataFrame:
                                                    0    \
0     {'barcode': '4011', 'description': 'ITEM NOT F...
1     {'barcode': '4011', 'description': 'ITEM NOT F...
2     {'needsFetchReview': False, 'partnerItemId': '...
3     {'barcode': '4011', 'description': 'ITEM NOT F...
4     {'barcode': '4011', 'description': 'ITEM NOT F...
...                                                 ...
1114  {'barcode': 'B076FJ92M4', 'description': 'muel...
1115                                               None
1116                                               None
1117  {'barcode': 'B076FJ92M4', 'description': 'muel...
1118                                               None

                                                    1     2     3     4    \
0                                                  None  None  None  None
1     {'barcode': '028400642255', 'description': 'DO...  None  None  None
2                                                  None  None  None  None
3                                                  None  None  None  None
4     {'barcode': '1234', 'finalPrice': '2.56', 'ite...  None  None  None
...                                                 ...   ...   ...   ...
1114  {'barcode': 'B07BRRLSVC', 'description': 'thin...  None  None  None
1115                                               None  None  None  None
1116                                               None  None  None  None
1117  {'barcode': 'B07BRRLSVC', 'description': 'thin...  None  None  None
1118                                               None  None  None  None

       5     6     7     8     9    ...   449   450   451   452   453   454  \
0     None  None  None  None  None  ...  None  None  None  None  None  None
1     None  None  None  None  None  ...  None  None  None  None  None  None
2     None  None  None  None  None  ...  None  None  None  None  None  None
3     None  None  None  None  None  ...  None  None  None  None  None  None
4     None  None  None  None  None  ...  None  None  None  None  None  None
...    ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
1114  None  None  None  None  None  ...  None  None  None  None  None  None
1115  None  None  None  None  None  ...  None  None  None  None  None  None
1116  None  None  None  None  None  ...  None  None  None  None  None  None
1117  None  None  None  None  None  ...  None  None  None  None  None  None
1118  None  None  None  None  None  ...  None  None  None  None  None  None

       455   456   457   458
0     None  None  None  None
1     None  None  None  None
2     None  None  None  None
3     None  None  None  None
4     None  None  None  None
...    ...   ...   ...   ...
1114  None  None  None  None
1115  None  None  None  None
1116  None  None  None  None
1117  None  None  None  None
1118  None  None  None  None

[1119 rows x 459 columns]

In [29]:

# Normalize rewardsReceiptItemList into a DataFrame
items_list = [item.get('rewardsReceiptItemList', []) for item in data]
items_df = pd.concat([pd.json_normalize(item) for item in items_list], ignore_index=True)

# Print the normalized DataFrame for 'rewardsReceiptItemList'
print("Normalized rewardsReceiptItemList DataFrame:")
print(items_df)

# If you want to analyze categorical values in normalized data:
# Identify columns with categorical data
categorical_columns = items_df.select_dtypes(include=['object']).columns

# Print list of categorical columns
print("\nCategorical columns in rewardsReceiptItemList:")
print(categorical_columns)

# Count distinct values in each categorical column
distinct_counts = items_df[categorical_columns].apply(pd.Series.nunique)

# Print distinct counts
print("\nNumber of distinct values in each categorical column in rewardsReceiptItemList:")
print(distinct_counts)

Normalized rewardsReceiptItemList DataFrame:
           barcode                                        description  \
0             4011                                     ITEM NOT FOUND
1             4011                                     ITEM NOT FOUND
2     028400642255  DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...
3              NaN                                                NaN
4             4011                                     ITEM NOT FOUND
...            ...                                                ...
6936    B07BRRLSVC  thindust summer face mask - sun protection nec...
6937    B076FJ92M4  mueller austria hypergrind precision electric ...
6938    B07BRRLSVC  thindust summer face mask - sun protection nec...
6939    B076FJ92M4  mueller austria hypergrind precision electric ...
6940    B07BRRLSVC  thindust summer face mask - sun protection nec...

     finalPrice itemPrice needsFetchReview partnerItemId  \
0         26.00     26.00            False             1
1             1         1              NaN             1
2         10.00     10.00             True             2
3           NaN       NaN            False             1
4         28.00     28.00            False             1
...         ...       ...              ...           ...
6936      11.99     11.99              NaN             1
6937      22.97     22.97              NaN             0
6938      11.99     11.99              NaN             1
6939      22.97     22.97              NaN             0
6940      11.99     11.99              NaN             1

     preventTargetGapPoints  quantityPurchased userFlaggedBarcode  \
0                      True                5.0               4011
1                       NaN                1.0                NaN
2                      True                1.0       028400642255
3                      True                NaN               4011
4                      True                4.0               4011
...                     ...                ...                ...
6936                    NaN                1.0                NaN
6937                    NaN                1.0                NaN
6938                    NaN                1.0                NaN
6939                    NaN                1.0                NaN
6940                    NaN                1.0                NaN

     userFlaggedNewItem  ... itemNumber  originalMetaBriteQuantityPurchased  \
0                  True  ...        NaN                                 NaN
1                   NaN  ...        NaN                                 NaN
2                  True  ...        NaN                                 NaN
3                  True  ...        NaN                                 NaN
4                  True  ...        NaN                                 NaN
...                 ...  ...        ...                                 ...
6936                NaN  ...        NaN                                 NaN
6937                NaN  ...        NaN                                 NaN
6938                NaN  ...        NaN                                 NaN
6939                NaN  ...        NaN                                 NaN
6940                NaN  ...        NaN                                 NaN

     pointsEarned targetPrice competitiveProduct originalFinalPrice  \
0             NaN         NaN                NaN                NaN
1             NaN         NaN                NaN                NaN
2             NaN         NaN                NaN                NaN
3             NaN         NaN                NaN                NaN
4             NaN         NaN                NaN                NaN
...           ...         ...                ...                ...
6936          NaN         NaN                NaN                NaN
6937          NaN         NaN                NaN                NaN
6938          NaN         NaN                NaN                NaN
6939          NaN         NaN                NaN                NaN
6940          NaN         NaN                NaN                NaN

     originalMetaBriteItemPrice deleted priceAfterCoupon metabriteCampaignId
0                           NaN     NaN              NaN                 NaN
1                           NaN     NaN              NaN                 NaN
2                           NaN     NaN              NaN                 NaN
3                           NaN     NaN              NaN                 NaN
4                           NaN     NaN              NaN                 NaN
...                         ...     ...              ...                 ...
6936                        NaN     NaN            11.99                 NaN
6937                        NaN     NaN            22.97                 NaN
6938                        NaN     NaN            11.99                 NaN
6939                        NaN     NaN            22.97                 NaN
6940                        NaN     NaN            11.99                 NaN

[6941 rows x 34 columns]

Categorical columns in rewardsReceiptItemList:
Index(['barcode', 'description', 'finalPrice', 'itemPrice', 'needsFetchReview',
       'partnerItemId', 'preventTargetGapPoints', 'userFlaggedBarcode',
       'userFlaggedNewItem', 'userFlaggedPrice', 'needsFetchReviewReason',
       'pointsNotAwardedReason', 'pointsPayerId', 'rewardsGroup',
       'rewardsProductPartnerId', 'userFlaggedDescription',
       'originalMetaBriteBarcode', 'originalMetaBriteDescription', 'brandCode',
       'competitorRewardsGroup', 'discountedItemPrice',
       'originalReceiptItemText', 'itemNumber', 'pointsEarned', 'targetPrice',
       'competitiveProduct', 'originalFinalPrice',
       'originalMetaBriteItemPrice', 'deleted', 'priceAfterCoupon',
       'metabriteCampaignId'],
      dtype='object')

Number of distinct values in each categorical column in rewardsReceiptItemList:
barcode                          568
description                     1889
finalPrice                       828
itemPrice                        828
needsFetchReview                   2
partnerItemId                    916
preventTargetGapPoints             1
userFlaggedBarcode                 6
userFlaggedNewItem                 1
userFlaggedPrice                  13
needsFetchReviewReason             2
pointsNotAwardedReason             1
pointsPayerId                     15
rewardsGroup                     182
rewardsProductPartnerId           16
userFlaggedDescription             3
originalMetaBriteBarcode           6
originalMetaBriteDescription       2
brandCode                        227
competitorRewardsGroup            30
discountedItemPrice              817
originalReceiptItemText         1738
itemNumber                        47
pointsEarned                     277
targetPrice                        2
competitiveProduct                 2
originalFinalPrice                 2
originalMetaBriteItemPrice         2
deleted                            1
priceAfterCoupon                 334
metabriteCampaignId               75
dtype: int64